goal_reached:
  reward: 15

safe_dist:
  punishment: 0.2

collision:
  punishment: 10

goal_approached:
  reward_factor: 0.5
  penalty_factor: 0.6

reverse_drive:
  penalty: 0.0001

# distance_global_plan:
#   reward_factor: 0.05
#   penalty_factor: 0.09

abrupt_vel_change:
  "0":
    vel_idx: 0
    factor: 0.3

  "-1":
    vel_idx: -1
    factor: 0.07

  "1":
    vel_idx: 1
    factor: 0.07

abrupt_forward_change:
  penalty: 0.025