# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  goal_radius: 0.4
  map_generator:
    barn:
      fill_pct: 0.05
      smooth_iter: 1
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 100
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
2:
  goal_radius: 0.25
  map_generator:
    barn:
      fill_pct: 0.05
      smooth_iter: 1
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 100
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
3:
  goal_radius: 0.25
  map_generator:
    barn:
      fill_pct: 0.1
      smooth_iter: 2
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 100
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
4:
  goal_radius: 0.25
  map_generator:
    barn:
      fill_pct: 0.1
      smooth_iter: 4
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 70
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
5:
  goal_radius: 0.25
  map_generator:
    barn:
      fill_pct: 0.1
      smooth_iter: 10
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 70
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
6:
  map_generator:
    barn:
      fill_pct: 0.15
      smooth_iter: 2
    rosnav:
      map_type: indoor
      indoor:
        corridor_radius: 5
        iterations: 50
      outdoor:
        obstacle_num: 5
        obstacle_extra_radius: 1
  static: 0
  dynamic: 0
7:
  map_generator:
    barn:
        fill_pct: 0.15
        smooth_iter: 4
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
8:
  map_generator:
    barn:
        fill_pct: 0.15
        smooth_iter: 10
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
9:
  map_generator:
    barn:
        fill_pct: 0.2
        smooth_iter: 2
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
10:
  map_generator:
    barn:
        fill_pct: 0.2
        smooth_iter: 4
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
11:
  map_generator:
    barn:
        fill_pct: 0.2
        smooth_iter: 6
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
12:
  map_generator:
    barn:
        fill_pct: 0.25
        smooth_iter: 2
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
13:
  map_generator:
    barn:
        fill_pct: 0.25
        smooth_iter: 4
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
14:
  map_generator:
    barn:
        fill_pct: 0.25
        smooth_iter: 6
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0
15:
  map_generator:
    barn:
        fill_pct: 0.3
        smooth_iter: 4
    rosnav:
        map_type: indoor
        indoor:
          corridor_radius: 5
          iterations: 30
        outdoor:
          obstacle_num: 5
          obstacle_extra_radius: 1
  static: 0
  dynamic: 0